w3c/webvtt

webvtt.html

This is almost equivalent as the "done positioning" step removes any
line boxes that do not completely fit inside the video, but as actually
implemented in at least Presto and Blink, it's the boxes in boxes which
are checked, not all of the boxes in output. Make this explicitly so.

Require the boxes in boxes, not output, to be within the title area box

---

webvtt.html

Instead of picking a "best position" which can both overlap other cues
and have lines outside the title area, simply discard cues when no
non-overlapping and contained position is found.
This achieves the "Don't overlap cues that don't fit" goal from
https://www.w3.org/Bugs/Public/show_bug.cgi?id=17483

Simplify snap-to-lines positioning to discard cues that don't fit

---

webvtt.html

This is consistent with many other uses of "be true" and "be false",
as in "Let cue's text track cue snap-to-lines flag be true."

Don't use quotes around 'true' as it is not a string

---

webvtt.html

This paragraph appears to conflate the writing direction, which is a
setting on the cue, with the paragraph embedding level and direction,
which are properties determined by applying the Unicode Bidirectional
Algorithm.
Introduced in commit 86ba250eaf7d2e53f614d684755ef13d089c7652.
Noticed due to https://www.w3.org/Bugs/Public/show_bug.cgi?id=28071

Remove inaccurate description of writing direction

---

webvtt.html

https://www.w3.org/Bugs/Public/show_bug.cgi?id=28070
This leaves the "Text track regions" section looking out of place:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28098

Rename the section on WebVTT cues

---

webvtt.html

All other links got directly to the single page spec and only this one
was to the multipage version.

Use consistent linking scheme to whatwg spec.

---

webvtt.html

For consistency also rename "WebVTT comment" to "WebVTT comment block",
since that is also a multi-line construct.
Also merge the WebVTT comments section into the file structure section,
since no other bits of syntax get their own section.

Rename the "WebVTT cue" syntax to "WebVTT cue block"

---

webvtt.html

This makes the section title consistent with cues:
https://github.com/w3c/webvtt/pull/173
However, all of the "text track region *" concepts are left intact, just
like the many WebVTT-specific "text track cue *" concepts. These all
need to be renamed as well.

Rename "text track region" to "WebVTT region"

---

publish.sh

cvs add fails if the file is already added, so add new images manually
when needed, which will be rarely.

Don't automatically add *.png to CVS

---

webvtt.html

It's very repetetive in cases like "A WebVTT cue has a WebVTT cue
computed line position" and isn't needed to disambiguate.
This is the first commit of several indented to separate the
defintitions as follows:
* "cue x" for the text track cue and WebVTT model
* "WebVTT cue x" for the syntax
* "vttcue-x" for the VTTCue API

Drop the WebVTT prefix from cue computed definitions

---

webvtt.html

The legal implications of "contribution" on IPR are far more involved
than what the actual contributions of the listed people were, in
particular with respect to patents. Avoid the word.
As requested in an email thread with Thierry, Philippe and David.

The word "contribution" has legal implications.

---

webvtt.html

Selectors Level 4 has a new definition for selectors:
http://www.w3.org/TR/selectors4/#syntax
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28472

Replace "group of selectors" with "selector".

---

webvtt.html

Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28470

Describe use case for DOM construction rules: getCueAsHTML

---

webvtt.html

Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28259

Disallow WebVTT metadata and cue settings zero length. 

---

webvtt.html

We could remove that sentence completely, since it's a surplus explanation. But I am aware that many people ask the question why not to pursue with an audio element, so it might be better to improve the sentence based on discussion at https://www.w3.org/Bugs/Public/show_bug.cgi?id=28511

Improve explanation when not to run the rendering algorithm.

---

webvtt.html

It isn't guaranteed to start at zero:
https://html.spec.whatwg.org/#media-timeline

Drop mention of media timeline origin

---

index.bs
index.html

The algorithm previously parsed ".1%" and "1.%" which is not consistent
with either HTML or CSS.

Fix #233: Parse a percentage string should fail for invalid input

---

index.bs
index.html

This allows the parser to fail fast for e.g. a long stream of data
that doesn't contain LF.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=22315.

Avoid waiting for a LF before checking the WEBVTT signature

---

index.bs
index.html

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28184.

Add 'text-combine-upright' to the list of supported CSS properties

---

index.bs
index.html

The rendering rules apply unicode-bidi:plaintext which isolates
each line. Make the definitions for "text alignment" start/end
match the rendering rules. Drop the "paragraph direction" concept
since it was not used for anything that changes the rendered result.

Fix #232: Make "text alignment" definitions match the rendering

---

index.bs
index.html

Add lots of notes and examples related to bidi issues. Also change
the style of sample cue rendering to make it stand out more.
The text is partially based on Richard Ishida's text in
https://github.com/w3c/webvtt/issues/227#issuecomment-154486613.

Fix #227: Explain how bidi works in WebVTT

---

index.bs
index.html

Make it possible for `<track srclang>` (or other external language)
to apply to the WebVTT nodes for the purpose of CSS `:lang()` matching,
glyph selection, etc.
"WebVTT cue text parsing rules" takes an optional fallback language.
The "rules for updating the display of WebVTT text tracks" also takes
an optional fallback language, since it is the entry point for HTML
and this algorithm then invokes the "WebVTT cue text parsing rules".
`getCueAsHTML()` does not provide a fallback language.
Fixes (1) in https://www.w3.org/Bugs/Public/show_bug.cgi?id=28255#c16.

Allow external language information to apply

---

index.bs
index.html

This hooks in to HTML's 'consume a character reference' for parsing,
and 'character references' for the syntax. All forms of charrefs
that HTML supports are supported, including missing semicolon.
(But missing semicolon is not valid, nor is a lone ampersand.)
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=23867.
Ref. #198.

Support all of HTML's character references

---

index.bs
index.html

Fix #260: Add a non-CSS UA conformance class

---

index.bs
index.html

Introduce a new "consume a WebVTT block" concept that is used
for parsing the header, cues, and discarding of bad cues.
This should be strictly editorial except that it also fixes #224.
It should be easier to add new block types like STYLE, and hopefully
easier to implement without having the algorithm use GOTO everywhere.

Fix #222: Revamp the parser

---

index.bs
index.html

The syntax allowed charrefs in annotations, but the tokenizer didn't.
Rename "HTML character reference state" to "HTML character reference
in data state" and add a new "HTML character reference in annotation
state". Switch into the new state when seeing "&" in the "WebVTT
start tag annotation state".
#252

Fix #252: Actually parse charrefs in annotation

---

index.bs
index.html

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=17218.
Also see https://github.com/w3c/webvtt/pull/274 -- if both of these changes are to be merged, the entire list should be removed.

Use overflow-wrap

---

index.bs
index.html

Fix #217: Clarify that only validators will validate language tags

---

index.bs
index.html

This affects align, position align, line align, and the DOM API.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=25956.

Rename "middle" to "center" throughout for consistency with CSS

---

index.bs
index.html

This makes region definitions more consistent with both STYLE
blocks as well as cue settings.
Issue: #231
cc @silviapfeiffer @eric-carlson

Fix #231: Switch to REGION blocks instead of headers

---

index.bs
index.html

* Make align:start/end not affect position or position alignment.
* Rename start/end for position alignment to left/right.
* Clarify what align:left/right do for vertical text.
Fixes:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28257#c9
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28257#c11
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28257#c13

Make position alignment saner

---

index.bs
index.html

The ruby text is rendered outside the background box, so by default,
if the video is white or very bright, the ruby text would be unreadable.

Fix #234: Use a default background for <rt>

---

index.bs
index.html

This appears to be fallout from
c08ed4197e59163104e779fd86f1af074245ee80.
Fixes https://github.com/w3c/webvtt/issues/226.
cc @alastor0325 @foolip

Editorial: remove unused variable 'current position score'

---

index.bs
index.html

Since 13e4a16b28dbecc062471f49b53f561f6d0d441c there are no defined
headers, so there being syntax defined for headers is confusing.
Fixes #304.

Editorial: Remove unused header syntax

---

index.bs
index.html

Non-integers can already enter the data model via the DOM API.
However, a valid WebVTT file can still only use integers.
Fixes #307.

Change parsing of 'line' setting to accept non-integers

---

index.bs

According to #310, the parser doesn't set the cue identifier to anything but the empty string. 
The fix is to set the cue identifier to buffer on cue creation.
@zcorpan, could you help me review this patch?
Thanks!

Modify the parsing rule to set the cue's identifier.

---

index.bs
index.html

No substantial changes are necessary to the rendering sections, since the new section is merely informative.
Some small cleanup of the rendering section title and subsectioning is included.
Closes #313 
Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28408

Add a section that explains the CSS extensions to authors.

---

index.bs
index.html

This variable was intended to ignore STYLE and REGION blocks after
having seen a cue, but it was never set to true.
Fixes #324.

Set |seen cue| to true when seeing a cue

---

index.bs
index.html

This makes line:-0 parse into +0 and ignores the setting if is
too big to represent as a finite number in IEEE 754.
Fixes #338.

Use HTML's rules for parsing floating-point number values

---

index.bs
index.html

Drop line: and position: settings with invalid linealign/colalign

---

index.bs
index.html

Editorial: Clarify CSS escapes in an example

---

index.bs
index.html

This actually introduces a definition for "WebVTT cue setting" and
clarifies how they provide information to position and align the cue
box and cue text.
Closes #360

Clarify the "WebVTT cue settings list" definition.

---

index.bs
index.html

Clarify line cue setting specification.

---

README.md
index.bs
index.html

This is to explain the box model and how settings work on cues and regions.
closes issue #383

Add some introductory paragraphs to the Data model section.

---

CODE_OF_CONDUCT.md
index.bs
index.html

Computed position alignment

---

index.bs
index.html

This actually introduces a definition for "WebVTT cue setting" and
clarifies how they provide information to position and align the cue
box and cue text.
Closes #361

Add a "User agents that do not support CSS" conformance class.

---

index.bs
index.html

Region lines cannot be negative now that they are unsigned long.

---

index.bs
index.html

Add a paragraph about the reasons why limiting styles.

---

archives/2018-04-15/Overview.html

Clarify relationship between CR and CG report

---

index.bs

Should be N/A per RFC 6838 Section 5.6.
***
<a href="https://pr-preview.s3.amazonaws.com/silviapfeiffer/webvtt-spec/pull/473.html" title="Last updated on Sep 10, 2019, 10:08 AM UTC (d3c0967)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webvtt/473/5ddbe7b...silviapfeiffer:d3c0967.html" title="Last updated on Sep 10, 2019, 10:08 AM UTC (d3c0967)">Diff</a>

Fixed the MIME Type specification part according to review by IANA.

---

w3c.json

This was found missing in https://w3c.github.io/validate-repos/report.html.

Add repo-type to w3c.json

---

index.bs

Added support for unbounded TextTrackCue - see https://github.com/whatwg/html/pull/5953
Whitespace removed by Atom
***
<a href="https://pr-preview.s3.amazonaws.com/away-team-software/webvtt/pull/493.html" title="Last updated on Apr 28, 2021, 4:01 PM UTC (0f46a24)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webvtt/493/6befe1d...away-team-software:0f46a24.html" title="Last updated on Apr 28, 2021, 4:01 PM UTC (0f46a24)">Diff</a>

Added unbounded TextTrackCue.endTime

---

index.bs

The `:past` and `:future` pseudo-classes are formally defined in Selectors 4, which the WebVTT spec correctly references. It is fine to re-define these terms locally. The problem is that previous commit flagged these definitions as being selectors, which is correct as well but also made Bikeshed export them.
In other words, these definitions now conflict with those in Selectors 4.
This update flags these definitions with a `noexport` attribute to tell Bikeshed to keep these definitions local.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/webvtt/pull/510.html" title="Last updated on Feb 27, 2023, 6:05 PM UTC (41d5e42)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webvtt/510/f6b3eab...tidoust:41d5e42.html" title="Last updated on Feb 27, 2023, 6:05 PM UTC …

[Editorial] Add "noexport" to :past and :future dfns

---

index.bs

The WebVTT specification contains examples that use a whitespace after the colon in a [WebVTT region width setting](https://www.w3.org/TR/webvtt1/#webvtt-region-width-setting) although the spec doesn't allow it. This PR removes these whitespace characters.
***
<a href="https://pr-preview.s3.amazonaws.com/dschuessler/webvtt/pull/527.html" title="Last updated on Jan 1, 2025, 3:35 PM UTC (1024baa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webvtt/527/aeaf117...dschuessler:1024baa.html" title="Last updated on Jan 1, 2025, 3:35 PM UTC (1024baa)">Diff</a>

Remove erroneous whitespace from code example
