webvtt.html

https://www.w3.org/Bugs/Public/show_bug.cgi?id=28074

Link to region in the text position definition

---

webvtt.html

https://www.w3.org/Bugs/Public/show_bug.cgi?id=27102
This doesn't actually define the WebVTT rules, that is for later.

Define the WebVTT rules for extracting the chapter title

---

webvtt.html

Mostly to avoid the question of a/an HTML..

Simplify WebVTT cue definition

---

webvtt.html

https://www.w3.org/Bugs/Public/show_bug.cgi?id=28666

Simplify the advice to author cues on a single line (sans "aesthetic")

---

webvtt.html

Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28073

Rename "line position" to "line offset".

---

webvtt.html

Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28259

Added a subsection in conformance that talks about unicode normalisation.

---

webvtt.html

Closes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28261

Adding explanation of how to interpret a WebVTT percentage to syntax.

---

webvtt.html

Addresses https://www.w3.org/Bugs/Public/show_bug.cgi?id=25542

Clean up WebVTT timestamp spec.

---

webvtt.html

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28073

Improve the wording around "line offset".

---

webvtt.html

Revert "Improve the wording around "line offset"."

---

webvtt.html

Revert "Revert "Improve the wording around "line offset".""

---

webvtt.html

https://github.com/w3c/webvtt/pull/197#issuecomment-129745804

Remove "cue" from some definitions

---

webvtt.html

closes issue 29165: https://www.w3.org/Bugs/Public/show_bug.cgi?id=29165

[issue 29165] updated to clarify positioning relationship to ruby.

---

index.bs
index.html

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=22154.

Refer to the HTML spec for which IDL interface elements use

---

index.bs
index.html

Restructure the Conformance section and actually define what the
different conformance classes are.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=29179.
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28524.

Define conformance classes better

---

index.bs
index.html

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28183.

Add 'ruby-position' to the lists of supported properties

---

index.bs
index.html

This is Simon Pieter's proposal with only minor typo fixes:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=15023#c31
------
This is @foolip's PR #185, only bikeshedded (prose is the same).

Add support for STYLE blocks (inline style)

---

index.bs
index.html

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=28432.

Use text-wrap:balance

---

index.bs
index.html

Fix #228: Add an example with classes and language change

---

index.bs
index.html

Fix #282: Fix the Unicode normalization example

---

index.bs
index.html

Editorial: clarify defaults for cue properties

---

index.bs
index.html

Update the rendering when line alignment/position alignment change

---

index.bs
index.html

Under 5.2. Step 2.4. match for viewportanchor, Step 5.: Update `WebVTT region anchor point` text to match link.

Fix for #325

---

index.bs
index.html

Fixes #327.
---
Thanks @BenjaminSchaaf; please take a look.

Add an EOF check before header

---

index.bs
index.html

Fixes #333. Also drive-by fix #330.

Throw IndexSizeError if VTTRegion lines is set to -1

---

index.bs
index.html

This has no normative effect but helps testing the IDL using
idlharness.js in web-platform-tests.

Editorial: Use IDL typedef for line and position members

---

index.bs
index.html

As proposed by David in https://github.com/w3c/webvtt/issues/323 .
There's also some cleanup using format.py

Add Security and Privay section

---

index.bs
index.html

Disallow external resources from data: URL resources in STYLE

---

index.bs
index.html

* Make sure regions only get created when they have an identifier
* introduce a ::cue-region(selector) pseudo-element
Addresses https://www.w3.org/Bugs/Public/show_bug.cgi?id=28471 and https://www.w3.org/Bugs/Public/show_bug.cgi?id=28474
Closes #314

Updates to region identifier, CSS selection & existance.

---

index.bs
index.html

Allow empty identifier for regions in the data model

---

index.bs
index.html

This is based on https://github.com/w3c/webvtt/pull/359 and can land after it. I'm adding myself as interim editor until we find a better person.

Add Silvia as editor

---

index.bs
index.html

Move definition of chapter title text to a more appropriate location.
Closes #362

Move definition of chapter title text

---

CODE_OF_CONDUCT.md

No ticket - PLH pointed out that we need code of conduct files on all repos, so this PR just adds one.

Add code of conduct as proposed by plh

---

index.bs
index.html

Also make the image display fully.
Fixes issue #385

Fix up algorithm markup and improve a bikeshed style.

---

index.bs
index.html

Turn long alt text into longdesc.

---

CODE_OF_CONDUCT.md
index.bs
index.html

Unsigned long issue414

---

index.bs
index.html

Also explain that their interpretation is done by the environment,
i.e. the software that uses the file.
Closes #363

Add some explanatory text about the different types of VTT files.

---

index.bs
index.html

Don't make edge margins depend on aesthetics.

---

archives/2018-04-15/Overview.html
archives/2018-04-15/changes.html

This brings the spec in line with the LICENSE.md file of the WebVTT repo
https://github.com/w3c/webvtt/blob/gh-pages/LICENSE.md

Use the W3C SOFTWARE AND DOCUMENT NOTICE AND LICENSE

---

index.bs
index.html

Fix typo in section 4.2.2

---

W3CTRMANIFEST.txt

ReSpec no longer supports ; ... this fixes auto-publishing through ECHIDNA.

chore(ECHIDNA): use & instead of ;

---

.github/workflows/deploy.yml

updated action's version, and fixed double --exclude=.gitignore in run line.

updated ghactions with JamesIves/github-pages-deploy-action@4.0.0

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/gkatsev/webvtt/pull/508.html" title="Last updated on Feb 27, 2023, 6:03 PM UTC (4b133b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webvtt/508/d7f514e...gkatsev:4b133b9.html" title="Last updated on Feb 27, 2023, 6:03 PM UTC (4b133b9)">Diff</a>

Update editor's affilitation
